# Use an official Nginx image as the base image
FROM nginx:latest

# Copy SSL certificate and key to the container
COPY ssl/server.crt /etc/nginx/conf.d/
COPY ssl/server.key /etc/nginx/conf.d/

# Copy the Nginx configuration file to the container
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose the HTTPS port
EXPOSE 443

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
