# Use an official Python runtime as the base image
FROM python:3.8-slim-buster

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        default-libmysqlclient-dev \
        libffi-dev \
        libssl-dev \
        libpq-dev \
        curl \
        netcat \
        postgresql-client \
        git \
    && rm -rf /var/lib/apt/lists/*

# Install Apache Airflow with extras
RUN pip install --no-cache-dir 'apache-airflow[postgres,mysql,crypto,jdbc]'

# Initialize the database
RUN airflow db init

# Create an admin user (replace with your own credentials)
RUN airflow users create \
    --username admin \
    --firstname Admin \
    --lastname User \
    --role Admin \
    --email admin@example.com \
    --password admin

# Expose the necessary Airflow ports
EXPOSE 8080 5555 8793

# Start the Airflow web server and scheduler
CMD ["airflow", "webserver", "--port", "8080"]
#CMD ["airflow", "scheduler"]
